{% set build = 0 %}
{% set strbuild = "build_" + build|string %}
{% set name = "ncrc" %}
{% set version = "1.22" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
    path: ../

build:
  number: {{ build }}
  string: {{ strbuild }}
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv --upgrade-strategy only-if-needed
  entry_points:
    - ncrc = ncrc.__main__:main

requirements:
  host:
    - python >=3.6
    - requests
    - conda
    - pip
  run:
    - python >=3.6
    - requests
    - conda

test:
  imports:
    - ncrc
  commands:
    - ncrc --help
    - ncrc search bison
    - ncrc list

about:
  home: https://github.com/idaholab/ncrc-client
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: Install Conda packages protected by an RSASecurID location
  doc_url: https://github.com/idaholab/ncrc-client
  dev_url: https://github.com/idaholab/ncrc-client

extra:
  recipe-maintainers:
    - milljm
